-- Removes the fixed UserRole enum entirely. Every user gets exactly one
-- Role instead (User.roleId, required), and the platform-operator flag
-- becomes its own column (isSuperAdmin) rather than a role value — it
-- belongs to no company and bypasses the permission system outright, so it
-- was never really "a role" in the RBAC sense.
--
-- Hand-written rather than autogenerated: this carries data across the
-- schema change (existing users' enum values -> matching Role rows), which
-- `prisma migrate dev` cannot express on its own. Written to run correctly
-- whether or not RbacService has already seeded these system Role rows on
-- a previous boot (find-by-name-first, never blind-insert) — see
-- RbacService.syncSystemRoles, which will find these rows already present
-- next boot and just keep their permissions in sync.
--
-- Not migrated: UserRoleAssignment rows (the "assign an extra role"
-- feature this replaces with a single required Role per user). This table
-- is dropped as-is; it only ever held rows in this environment's own
-- development/testing, not in any real tenant's data.

-- AlterTable: platform-operator flag, independent of the Role system.
ALTER TABLE "User" ADD COLUMN "isSuperAdmin" BOOLEAN NOT NULL DEFAULT false;
UPDATE "User" SET "isSuperAdmin" = true WHERE "role" = 'SUPER_ADMIN';

-- AlterTable: branch-scoping moves from a hardcoded role check to a flag on
-- Role itself, so a tenant's own custom role can opt into it too.
ALTER TABLE "Role" ADD COLUMN "isBranchScoped" BOOLEAN NOT NULL DEFAULT false;

-- Ensure every system Role this migration needs to point users at exists,
-- without duplicating one RbacService already created on a prior boot.
INSERT INTO "Role" (id, name, description, "isSystem", "isBranchScoped", "companyId", "createdAt", "updatedAt")
SELECT gen_random_uuid(), v.name, v.description, true, v."isBranchScoped", NULL, now(), now()
FROM (VALUES
    ('Super Admin', 'Built-in role matching the legacy "SUPER_ADMIN" access level.', false),
    ('Company Admin', 'Built-in role matching the legacy "COMPANY_ADMIN" access level.', false),
    ('Sales Head', 'Built-in role matching the legacy "SALES_HEAD" access level.', true),
    ('Sales Manager', 'Built-in role matching the legacy "SALES_MANAGER" access level.', true),
    ('Finance', 'Built-in role matching the legacy "FINANCE" access level.', false)
) AS v(name, description, "isBranchScoped")
WHERE NOT EXISTS (
    SELECT 1 FROM "Role" r WHERE r."companyId" IS NULL AND r.name = v.name
);

-- A system role that already existed from a previous boot (created before
-- this migration) still needs the new isBranchScoped flag set correctly.
UPDATE "Role" SET "isBranchScoped" = true
WHERE "companyId" IS NULL AND name IN ('Sales Head', 'Sales Manager');

-- AlterTable: the new required FK, backfilled from the old enum column by
-- matching each legacy value to its system Role's name.
ALTER TABLE "User" ADD COLUMN "roleId" TEXT;

UPDATE "User" u SET "roleId" = r.id
FROM "Role" r
WHERE r."companyId" IS NULL
  AND r.name = CASE u."role"
      WHEN 'SUPER_ADMIN' THEN 'Super Admin'
      WHEN 'COMPANY_ADMIN' THEN 'Company Admin'
      WHEN 'SALES_HEAD' THEN 'Sales Head'
      WHEN 'SALES_MANAGER' THEN 'Sales Manager'
      WHEN 'FINANCE' THEN 'Finance'
  END;

ALTER TABLE "User" ALTER COLUMN "roleId" SET NOT NULL;

-- DropForeignKey / DropTable: the "assign an extra role" many-to-many this
-- migration replaces with the single required roleId above.
ALTER TABLE "UserRoleAssignment" DROP CONSTRAINT IF EXISTS "UserRoleAssignment_userId_fkey";
ALTER TABLE "UserRoleAssignment" DROP CONSTRAINT IF EXISTS "UserRoleAssignment_roleId_fkey";
DROP TABLE "UserRoleAssignment";

-- DropColumn / DropEnum: the enum this whole migration exists to remove.
ALTER TABLE "User" DROP COLUMN "role";
DROP TYPE "UserRole";

-- AddForeignKey / CreateIndex for the new required relation.
ALTER TABLE "User" ADD CONSTRAINT "User_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "User_roleId_idx" ON "User"("roleId");
