-- AlterEnum
ALTER TYPE "ActivityAction" ADD VALUE 'CREATED_USER';
ALTER TYPE "ActivityAction" ADD VALUE 'UPDATED_USER';
ALTER TYPE "ActivityAction" ADD VALUE 'ROLE_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE 'DEACTIVATED_USER';
ALTER TYPE "ActivityAction" ADD VALUE 'RESET_PASSWORD';
ALTER TYPE "ActivityAction" ADD VALUE 'REVOKED_SESSIONS';

-- AlterEnum
ALTER TYPE "ActivityType" ADD VALUE 'USER_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'USER_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'USER_ROLE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE 'USER_BRANCH_TRANSFERRED';
ALTER TYPE "ActivityType" ADD VALUE 'USER_DEACTIVATED';
ALTER TYPE "ActivityType" ADD VALUE 'USER_PASSWORD_RESET';
ALTER TYPE "ActivityType" ADD VALUE 'USER_SESSIONS_REVOKED';

-- AlterTable
ALTER TABLE "Activity" ADD COLUMN     "targetUserId" TEXT;

-- CreateIndex
CREATE INDEX "Activity_targetUserId_idx" ON "Activity"("targetUserId");

-- AddForeignKey
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_targetUserId_fkey" FOREIGN KEY ("targetUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
