-- AlterEnum
ALTER TYPE "ActivityAction" ADD VALUE 'REACTIVATED_USER';
ALTER TYPE "ActivityAction" ADD VALUE 'CHANGED_PASSWORD';

-- AlterEnum
ALTER TYPE "ActivityType" ADD VALUE 'USER_REACTIVATED';
ALTER TYPE "ActivityType" ADD VALUE 'USER_PASSWORD_CHANGED';
